name: speaky_chat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
    # sdk: flutter

  app_links: 3.4.1
#  assets_audio_player: 3.1.1
#  assets_audio_player_web: 3.1.1
  audioplayers: ^6.0.0
  auto_size_text: 3.0.0

  blurhash_dart: 1.2.1
  build_runner: 2.4.9
  blur: ^3.1.0
  video_trimmer: ^3.0.0
  cached_network_image: 3.3.1
  cloud_firestore: ^4.15.10
  contacts_service: ^0.6.3

  camera: ^0.10.5+9
  camerawesome: ^2.0.1

  connectivity_plus: ^5.0.0

  dropdown_button2: 2.3.9
  device_info_plus: ^9.1.2
  double_tap_to_exit: ^1.0.1

  equatable: 2.0.5
  emoji_picker_flutter: ^2.2.0
  external_path: ^1.0.3


  file_picker: ^8.0.0+1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  firebase_storage: ^11.6.10
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.1
  flutter_contacts: ^1.1.8
  firebase_database: ^10.5.1
  flutter_session_manager: ^1.0.3
  flutter_plugin_android_lifecycle: 2.0.17
  fluttertoast: ^8.2.6
  flutter_svg: ^2.0.9
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  functions_client: 1.3.2

  go_router: 7.1.1
  google_fonts: 4.0.3
  gotrue: 1.12.6
  get: ^4.6.6
  # gallery_picker: ^0.5.1
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0

  hive: 2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^0.13.6

  image: 4.1.3

  gap: ^3.0.1

  media_scanner: ^2.1.0

#  just_audio: ^0.9.37
  image_picker: ^1.0.7
  image_picker_android: 0.8.8
  image_picker_for_web: 3.0.1
  image_picker_ios: 0.8.8+2
  image_picker_platform_interface: 2.9.1
  intl:
  json_path: 0.6.2
  lottie: 2.7.0
  mime_type: 1.0.0
  octo_image: 2.0.0
  back_pressed: ^0.0.2
#  open_file: ^3.3.2
  open_file_plus: ^3.4.1+1
  page_transition: 2.1.0
  path_provider: 2.1.2
  path_provider_android: 2.1.0
  path_provider_foundation: 2.3.2
  path_provider_platform_interface: 2.1.0
  permission_handler: ^11.3.1
  photo_view: 0.14.0
  pin_code_fields: 8.0.1
  plugin_platform_interface: 2.1.8
  postgrest: 1.5.2
  provider: 6.0.5
  realtime_client: 1.4.0
#  record: ^5.0.5
  record: ^5.1.1
  record_mp3: ^3.0.0
  rxdart: 0.27.7
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  swiper_detector: ^0.0.1
#  sign_in_with_apple: 6.0.0
#  sign_in_with_apple_platform_interface: 1.0.0
#  sign_in_with_apple_web: 1.0.1
  sqflite: 2.2.6
  stop_watch_timer: 3.0.2
  storage_client: 1.5.4
  supabase: 1.11.11
  supabase_flutter: 1.10.24
#  socket_io_client: ^2.0.3+1
  timeago: ^3.7.0
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  video_player: 2.8.4
  video_player_android: 2.4.10
  video_player_avfoundation: 2.5.1
  video_player_platform_interface: 6.2.1
  video_player_web: 2.1.2
#  video_thumbnail: ^0.5.1
  video_compress: ^3.1.2
#  voice_message_package:
#    #    path: ../voice_message_player-code-with-bisky
#    git:
#      url: https://github.com/codewithbisky/voice_message_player.git
#      ref: master

#  voice_message_package: ^2.1.4
  webview_flutter: 4.0.5
  webview_flutter_android: 3.3.1
  webview_flutter_platform_interface: 2.0.2
  webview_flutter_wkwebview: 3.1.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  story_view: ^0.16.5
  dio: ^5.5.0+1
  flutter_spinkit: ^5.2.1
  agora_rtc_engine: ^6.3.2

dependency_overrides:
  rxdart: 0.27.7

dev_dependencies:
  flutter_lints: 3.0.0
  lints: 3.0.0

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/icons/
  fonts:
    - family: 'Arial Rounded MT Bold'
      fonts:
        - asset: assets/fonts/ARLRDBD.ttf
    - family: ' Comic Sans MS'
      fonts:
        - asset: assets/fonts/COMIC.TTF

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
