// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzrJyBUyRl_JfoQFnw7j-W_JeNyPiwiDU',
    appId: '1:996855514631:web:a3f6de3266a46274fe8ca2',
    messagingSenderId: '996855514631',
    projectId: 'speakychat-e2f70',
    authDomain: 'speakychat-e2f70.firebaseapp.com',
    storageBucket: 'speakychat-e2f70.appspot.com',
    measurementId: 'G-MPZRQKK88J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC13FXK4WsRFmcg-FXzOz-yeBOqLZTgbNM',
    appId: '1:616385244627:android:29988ce934d7fc4b8b9326',
    messagingSenderId: '616385244627',
    projectId: 'speaky-chat0',
    storageBucket: 'speaky-chat0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAORqBX-9qt_g2NBETQWaU-JFHa7hEpTyA',
    appId: '1:616385244627:ios:f0e723a51fa3b62c8b9326',
    messagingSenderId: '616385244627',
    projectId: 'speaky-chat0',
    storageBucket: 'speaky-chat0.appspot.com',
    iosBundleId: 'com.mycompany.speakychat',
  );

}